# Generated by Django 5.2.7 on 2025-12-08 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('jurisdiction_area', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to='account.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_unit', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Medical', 'Medical Responders'), ('Fire', 'Fire Responders'), ('Law', 'Law Enforcement Responders'), ('Rescue', 'Rescue & Search Responders'), ('Logistics', 'Logistics & Support Responders'), ('Community', 'Community Responders')], max_length=15)),
                ('service_area', models.CharField(max_length=50)),
                ('duty_status', models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off Duty'), ('CALL', 'On Call'), ('RES', 'Responding'), ('UNAV', 'Unavailable'), ('REL', 'Released')], default='OFF', max_length=10)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to='account.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority'), ('responder', 'Responder')], default='citizen', max_length=20)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_emails', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='account.user')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to='account.user'),
        ),
    ]
