# Generated by Django 5.2.7 on 2025-11-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('jurisdiction_area', models.CharField(max_length=50)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_unit', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Medical', 'Medical Responders'), ('Fire', 'Fire Responders'), ('Law', 'Law Enforcement Responders'), ('Rescue', 'Rescue & Search Responders'), ('Logistics', 'Logistics & Support Responders'), ('Community', 'Community Responders')], max_length=15)),
                ('service_area', models.CharField(max_length=50)),
                ('duty_status', models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off Duty'), ('CALL', 'On Call'), ('RES', 'Responding'), ('UNAV', 'Unavailable'), ('REL', 'Released')], default='OFF', max_length=10)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
