# Generated by Django 5.2.7 on 2025-12-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority'), ('responder', 'Responder')], default='citizen', max_length=20),
        ),
        migrations.AlterField(
            model_name='authority',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to='account.citizen'),
        ),
    ]
