# Generated by Django 5.2.7 on 2025-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_account_alter_citizen_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
