# Generated by Django 5.2.7 on 2025-12-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role_alter_authority_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
