# Generated by Django 6.0 on 2025-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_calllog_responder_alter_calllog_emergency_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='ringing', max_length=20),
        ),
    ]
