# Generated by Django 5.2.7 on 2025-12-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentdocument',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
