# Generated by Django 5.2.7 on 2025-10-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('medical', 'Medical Emergency'), ('crime', 'Crime/Violence'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('gps_location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='account.authority')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='account.responder')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='account.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='EventAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('authority', 'Authority'), ('responder', 'Responder')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_assignments', to='account.authority')),
                ('emergency_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='emergency.emergencyevent')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_assignments', to='account.responder')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
